In [ ]:
# Coding the Currency Conversion Problem

First you will need to create the inputs vector that holds the currency you have from the eight countries into a numpy vector. To begin, first import the NumPy package and then use the package to create a vector from a list. Next we convert the vector into a pandas dataframe so that it will print out nicely below with column labels to indicate the country the currency amount is associated to.

In [4]:
import numpy as np
import pandas as pd

# money inputs from those countries, goes to a comversion rate a matrix and is outputed as total money

# Create numpy vector from a list to represent money (inputs) vector.
money = np.asarray([70, 100, 20, 80, 40, 70, 60, 100])

# Creates pandas dataframe with column labels(currency_label) from the numpy vector for printing.
currency_label = ["USD", "EUR", "JPY", "GBP", "CHF", "CAD", "AUD", "HKD"]
money_df = pd.DataFrame(data = money, index = currency_label, columns = ["Amounts"])
print("Input Vector:")
money_df

Input Vector:

     Amounts
USD       70
EUR      100
JPY       20
GBP       80
CHF       40
CAD       70
AUD       60
HKD      100

Next we need to create the weights matrix by importing the currency conversion rates matrix. We will use python package Pandas to quickly read in the matrix and approriately assign row and column labels. Additionally, we define a variable path to define the location of the currency conversion matrix. The code below imports this weights matrix, converts the dataframe into a numpy matrix, and displays its content to help you determine how to solve the problem using matrix multiplication.

In [8]:
# Sets path variable to the 'path' of the CSV file that contains the conversion rates(weights) matrix.
path = %pwd

# Imports conversion rates(weights) matrix as a pandas dataframe.
conversion_rates_df = pd.read_csv(path+"/currencyConversionMatrix.csv",header=0,index_col=0)

# Creates numpy matrix from a pandas dataframe to create the conversion rates(weights) matrix.
conversion_rates = conversion_rates_df.values
# conversion_rates

# Prints conversion rates matrix.
print("Weights Matrix:")
conversion_rates_df

Weights Matrix:

           USD     EUR       JPY     GBP     CHF     CAD     AUD      HKD
USD-To  1.0000  0.8364  111.3700  0.7404  0.9781  1.2548  1.2760   7.8218
EUR-To  1.1956  1.0000  133.1540  0.8852  1.1694  1.5002  1.5256   9.3517
JPY-To  0.0090  0.0075    1.0000  0.0066  0.0088  0.0113  0.0115   0.0702
GBP-To  1.3507  1.1297  150.4275  1.0000  1.3211  1.6949  1.7235  10.5649
CHF-To  1.0224  0.8551  113.8636  0.7569  1.0000  1.2829  1.3046   7.9969
CAD-To  0.7969  0.6666   88.7552  0.5900  0.7795  1.0000  1.0169   6.2335
AUD-To  0.7837  0.6555   87.2807  0.5802  0.7665  0.9834  1.0000   6.1299
HKD-To  0.1278  0.1069   14.2384  0.0947  0.1250  0.1604  0.1631   1.0000

use the function matmul for multiplying money and conversion_rates to compute the vector money_totals. Recall that we used the alias np when we imported the Numpy package above, so be certain to use the np alias when calling the matmul function below. Additionally, be certain to select 'Cell' and 'Run All' to check the code you insert below.

In [9]:
# Done.: Calculates the money totals(outputs) vector using matrix multiplication in numpy.
money_totals = np.matmul(money, conversion_rates)

# Converts the resulting money totals vector into a dataframe for printing.
money_totals_df = pd.DataFrame(data = money_totals, index = currency_label, columns = ["Money Totals"])
print("Outputs Vector:")
money_totals_df

Outputs Vector:

     Money Totals
USD       454.277
EUR       379.960
JPY     50593.590
GBP       336.338
CHF       444.326
CAD       570.034
AUD       579.667
HKD      3553.307